//POST
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";
export const GET_USER_POSTS_BEGIN = "GET_USER_POSTS_BEGIN";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_ERROR = "GET_USER_POSTS_ERROR";
export const LOAD_ALL_POSTS = "LOAD_ALL_POSTS";
export const SET_GRIDVIEW = "SET_GRIDVIEW";
export const SET_LISTVIEW = "SET_LISTVIEW";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";

//UPLOAD
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";

//INTERACTION
export const FOLLOW_UNFOLLOW_FRIEND = "FOLLOW_UNFOLLOW_FRIEND";
export const LIKE_DISLIKE_POST = "LIKE_DISLIKE_POST";
export const CHECK_FRIEND_PROFILE = "CHECK_FRIEND_PROFILE";
export const COMMENT_ON_POST = "COMMENT_ON_POST";
export const STAR_FRIEND_PROFILE = "STAR_FRIEND_PROFILE";
export const RUN_HASHTAG = "RUN_HASHTAG";

// auth
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const SET_USER_FROM_STORAGE = "SET_USER_FROM_STORAGE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const AUTH_USER_BEGIN = "AUTH_USER_BEGIN";
export const AUTH_USER_ERROR = "AUTH_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
